// Date: 21-10-2013 13:03:06
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.ivorius.planefighter;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlanewings2 extends ModelBase
{
	//fields
	ModelRenderer wingbeamleft1;
	ModelRenderer wingbeamright1;
	ModelRenderer wingleft1;
	ModelRenderer wingright1;
	ModelRenderer wingbeamleft2;
	ModelRenderer wingbeamright2;
	ModelRenderer wingleft2;
	ModelRenderer wingright2;

	public ModelPlanewings2()
	{
		textureWidth = 128;
		textureHeight = 64;

		wingbeamleft1 = new ModelRenderer(this, 0, 30);
		wingbeamleft1.addBox(0F, -1F, -2F, 8, 1, 1);
		wingbeamleft1.setRotationPoint(1F, 20F, -3F);
		wingbeamleft1.setTextureSize(128, 64);
		wingbeamleft1.mirror = true;
		setRotation(wingbeamleft1, 0F, 0.2602503F, 0F);
		wingbeamright1 = new ModelRenderer(this, 19, 30);
		wingbeamright1.addBox(-8F, -1F, -2F, 8, 1, 1);
		wingbeamright1.setRotationPoint(-1F, 20F, -3F);
		wingbeamright1.setTextureSize(128, 64);
		wingbeamright1.mirror = true;
		setRotation(wingbeamright1, 0F, -0.260246F, 0F);
		wingleft1 = new ModelRenderer(this, 0, 33);
		wingleft1.addBox(0F, -0.5F, -2F, 11, 0, 5);
		wingleft1.setRotationPoint(1F, 20F, -3F);
		wingleft1.setTextureSize(128, 64);
		wingleft1.mirror = true;
		setRotation(wingleft1, 0F, 0.260246F, 0F);
		wingright1 = new ModelRenderer(this, 30, 33);
		wingright1.addBox(-11F, -0.5F, -2F, 11, 0, 5);
		wingright1.setRotationPoint(-1F, 20F, -3F);
		wingright1.setTextureSize(128, 64);
		wingright1.mirror = true;
		setRotation(wingright1, 0F, -0.260246F, 0F);
		wingbeamleft2 = new ModelRenderer(this, 0, 39);
		wingbeamleft2.addBox(-0.5F, -0.5F, 1F, 7, 1, 1);
		wingbeamleft2.setRotationPoint(1F, 20F, -3F);
		wingbeamleft2.setTextureSize(128, 64);
		wingbeamleft2.mirror = true;
		setRotation(wingbeamleft2, 0F, 0F, -0.2974289F);
		wingbeamright2 = new ModelRenderer(this, 17, 39);
		wingbeamright2.addBox(-6.5F, -0.5F, 1F, 7, 1, 1);
		wingbeamright2.setRotationPoint(-1F, 20F, -3F);
		wingbeamright2.setTextureSize(128, 64);
		wingbeamright2.mirror = true;
		setRotation(wingbeamright2, 0F, 0F, 0.2974216F);
		wingleft2 = new ModelRenderer(this, 0, 42);
		wingleft2.addBox(0F, 0F, 1F, 9, 0, 4);
		wingleft2.setRotationPoint(1F, 20F, -3F);
		wingleft2.setTextureSize(128, 64);
		wingleft2.mirror = true;
		setRotation(wingleft2, 0F, 0F, -0.2974216F);
		wingright2 = new ModelRenderer(this, 25, 42);
		wingright2.addBox(-9F, 0F, 1F, 9, 0, 4);
		wingright2.setRotationPoint(-1F, 20F, -3F);
		wingright2.setTextureSize(128, 64);
		wingright2.mirror = true;
		setRotation(wingright2, 0F, 0F, 0.2974216F);
	}

	public void render( Entity entity, float f, float f1, float f2, float f3, float f4, float f5 )
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		wingbeamleft1.render(f5);
		wingbeamright1.render(f5);
		wingleft1.render(f5);
		wingright1.render(f5);
		wingbeamleft2.render(f5);
		wingbeamright2.render(f5);
		wingleft2.render(f5);
		wingright2.render(f5);
	}

	private void setRotation( ModelRenderer model, float x, float y, float z )
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
