// Date: 21-10-2013 13:22:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.ivorius.planefighter;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlaneguns2 extends ModelBase
{
	//fields
	ModelRenderer gun1;
	ModelRenderer gun2;

	public ModelPlaneguns2()
	{
		textureWidth = 128;
		textureHeight = 64;

		gun1 = new ModelRenderer(this, 0, 51);
		gun1.addBox(-0.5F, 1.5F, -6F, 1, 1, 5);
		gun1.setRotationPoint(0F, 20F, -3F);
		gun1.setTextureSize(128, 64);
		gun1.mirror = true;
		setRotation(gun1, 0F, 0F, 0F);
		gun2 = new ModelRenderer(this, 0, 48);
		gun2.addBox(-1.5F, 2F, -3F, 3, 2, 0);
		gun2.setRotationPoint(0F, 20F, -3F);
		gun2.setTextureSize(128, 64);
		gun2.mirror = true;
		setRotation(gun2, -0.4089647F, 0F, 0F);
	}

	public void render( Entity entity, float f, float f1, float f2, float f3, float f4, float f5 )
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		gun1.render(f5);
		gun2.render(f5);
	}

	private void setRotation( ModelRenderer model, float x, float y, float z )
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
