// Date: 20-10-2013 23:12:58
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.ivorius.planefighter;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlaneguns1 extends ModelBase
{
	//fields
	ModelRenderer gunleft;
	ModelRenderer gunright;
	ModelRenderer midpiece;

	public ModelPlaneguns1()
	{
		textureWidth = 128;
		textureHeight = 64;

		gunleft = new ModelRenderer(this, 0, 52);
		gunleft.addBox(0.5F, 0.7F, -5F, 1, 1, 4);
		gunleft.setRotationPoint(0F, 20F, -3F);
		gunleft.setTextureSize(128, 64);
		gunleft.mirror = true;
		setRotation(gunleft, 0F, -0.0743572F, 0.2648976F);
		gunright = new ModelRenderer(this, 11, 52);
		gunright.addBox(-1.5F, 0.7F, -5F, 1, 1, 4);
		gunright.setRotationPoint(0F, 20F, -3F);
		gunright.setTextureSize(128, 64);
		gunright.mirror = true;
		setRotation(gunright, 0F, 0.074351F, -0.2649061F);
		midpiece = new ModelRenderer(this, 0, 58);
		midpiece.addBox(-1.5F, -2F, -4.5F, 3, 0, 1);
		midpiece.setRotationPoint(0F, 20F, -3F);
		midpiece.setTextureSize(128, 64);
		midpiece.mirror = true;
		setRotation(midpiece, 0.7063936F, 0F, 0F);
	}

	public void render( Entity entity, float f, float f1, float f2, float f3, float f4, float f5 )
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		gunleft.render(f5);
		gunright.render(f5);
		midpiece.render(f5);
	}

	private void setRotation( ModelRenderer model, float x, float y, float z )
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
